# Use a lightweight web server image
FROM nginx:alpine

# Copy the HTML files to the container
COPY index.html /usr/share/nginx/html/
COPY test.html /usr/share/nginx/html/

COPY assets/ /usr/share/nginx/html/assets/
# Expose the default HTTP port
EXPOSE 80

# Start the Nginx web server
CMD ["nginx", "-g", "daemon off;"]
